export const scenes = [
  {
    slug: 'korean-baseball-broadcast',
    title: '韩国棒球直播风格',
    hot: true,
    price: 2.99,
    bundle: 5.99,
    gradient: 'linear-gradient(135deg,#25122e,#f65f9a 55%,#ffe9ac)',
    description: '上传自拍，生成像被韩国棒球赛直播镜头捕捉到的看球现场照片。',
    subtitle: '像真的被体育直播拍到，适合小红书、抖音和朋友圈晒图。',
    tags: ['爆款', '女生适合', '直播感', '韩国棒球'],
    tips: ['正脸或半身照效果最好', '光线清晰', '避免多人合照'],
  },
  {
    slug: 'tokyo-night-street',
    title: '东京夜景街拍',
    hot: true,
    price: 2.99,
    bundle: 5.99,
    gradient: 'linear-gradient(135deg,#15192e,#6257ff 48%,#ff93cb)',
    description: '把普通自拍变成东京街头霓虹夜景里的电影感街拍。',
    subtitle: '适合头像、朋友圈九宫格、旅行感虚拟照片。',
    tags: ['夜景', '东京', '街拍'],
    tips: ['半身照效果更自然', '面部清晰', '服装轮廓明显'],
  },
  {
    slug: 'japanese-sakura-street',
    title: '日本樱花街拍',
    hot: true,
    price: 2.99,
    bundle: 5.99,
    gradient: 'linear-gradient(135deg,#ffd6e8,#fff5fb 45%,#9bd8b8)',
    description: '上传一张照片，获得春日樱花街道里的清透日系写真。',
    subtitle: '轻旅行感、春日感、适合女生头像。',
    tags: ['樱花', '日系', '春日'],
    tips: ['浅色衣服更容易出片', '表情自然', '单人照片优先'],
  },
  {
    slug: 'kpop-concert-audience',
    title: 'K-pop 演唱会观众席',
    hot: true,
    price: 2.99,
    bundle: 5.99,
    gradient: 'linear-gradient(135deg,#1d1036,#a855f7 45%,#22d3ee)',
    description: '生成仿佛你在演唱会内场被灯光照亮的追星现场照片。',
    subtitle: '舞台灯、荧光棒、人群光海。',
    tags: ['K-pop', '追星', '演唱会'],
    tips: ['脸部不要过暗', '避免复杂背景', '自拍或半身照均可'],
  },
  {
    slug: 'hong-kong-retro-portrait',
    title: '港风复古写真',
    hot: false,
    price: 2.99,
    bundle: 5.99,
    gradient: 'linear-gradient(135deg,#392311,#d55b3d 42%,#ffd18a)',
    description: '把照片转成港风电影海报感的复古人像。',
    subtitle: '胶片色、霓虹、老街、复古镜头语言。',
    tags: ['港风', '复古', '电影感'],
    tips: ['五官清晰', '侧脸或正脸均可', '深色服装也适合'],
  },
  {
    slug: 'european-football-stand',
    title: '欧洲足球看台',
    hot: false,
    price: 2.99,
    bundle: 5.99,
    gradient: 'linear-gradient(135deg,#06351f,#28c76f 48%,#fff1a8)',
    description: '生成像在欧洲足球赛现场看台被镜头捕捉的照片。',
    subtitle: '球场、人群、绿色草坪、现场欢呼感。',
    tags: ['足球', '看台', '欧洲'],
    tips: ['上半身清楚', '表情自然', '运动风服装更适合'],
  },
];

export function publicScenes() {
  return scenes.map(({ hiddenPrompt, hiddenNegativePrompt, ...scene }) => scene);
}
